"""
code_semantic_context_models.py
--------------------------
Purpose:
  Defines core data structures and types used by the semantic-context pipeline.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Literal, Set, Tuple

from code_context_mangers.code_context_orchestrator import ContextBlock

# Literal type used to keep command values type-safe.
CommandType = Literal["get_definition", "get_type_definition", "get_references", "get_search"]

@dataclass
class SemanticCommand:
    """
    Stores the state of one LLM-generated command, including raw input,
    normalized fields, validation state, and execution result.
    """
    # --- Raw input ---
    raw_command: str  # Raw command string generated by the LLM, e.g., "get_references()"
    raw_line: str  # Raw line string specified by the LLM, e.g., "55" or "line 55"
    raw_target_symbol: str  # Raw target symbol identified by the LLM, e.g., "isLocalFile"

    # --- Normalized and validated fields ---
    command_type: Optional[CommandType] = None  # Mapped standard command type.
    target_symbol: Optional[str] = None  # Cleaned target symbol.
    line_num: Optional[int] = None  # Parsed and validated line number (1-based).
    cursor: Optional[int] = None

    # --- Actual execution file, line, and cursor ---
    exec_path: Optional[str] = None
    exec_line_num: Optional[int] = None
    exec_cursor: Optional[int] = None

    # --- Processing state ---
    is_valid: bool = False  # Whether the command passed validation.
    error_message: Optional[str] = None  # Reason recorded when invalid.

    # --- Execution result ---
    lsp_result: Optional[Dict] = None  # Raw result returned by the LSP query.

    # --- Rule-source flags / source set / modified-line filter requirement ---
    rule_flags: Dict[str, bool] = field(default_factory=dict)  # e.g. {"Rule-1": False, "Rule-2": True}
    source_rules: Set[str] = field(default_factory=set)  # e.g. {"Rule-7", "Rule-3"}
    requires_modified_line: bool = True  # Set to False when the source includes Rule-3.

    def identity_key(self):
        """Commands with the same normalized command, line, and cursor are treated as identical."""
        return (self.command_type, self.line_num, self.cursor)

    def __str__(self):
        return f"Raw: <{self.raw_command}, {self.raw_line}, {self.raw_target_symbol}>; " \
               f"Format: <{self.command_type}, {self.line_num}, {self.cursor}, {self.target_symbol}>" \
               f"Rules: {sorted(self.source_rules)}; "

    def get_format_cmd(self):
        return f"<CMD={self.command_type}, L={self.line_num}, C={self.cursor}, S={self.target_symbol}>"

@dataclass
class BlockProvenance:
    """Provenance metadata for a semantic block."""
    command_types: Set[str] = field(default_factory=set)      # {"get_definition"}
    target_symbols: Set[str] = field(default_factory=set)     # {"isLocalFile"}
    source_rules: Set[str] = field(default_factory=set)       # {"Rule-7"}

    status: str = "kept"              # "kept" / "trimmed" / "discarded"
    discard_reason: str = ""          # Reason for discarding the block.
    original_range: Optional[Tuple[int, int]] = None  # (start_line, end_line) before trimming.

    def merge(self, other: 'BlockProvenance'):
        self.command_types |= other.command_types
        self.target_symbols |= other.target_symbols
        self.source_rules |= other.source_rules


@dataclass
class CommandBlockGroup:
    """Helper object linking one source command to all blocks it generated."""
    source_command: SemanticCommand
    generated_blocks: List[ContextBlock]
    block_provenances: Dict[int, BlockProvenance] = field(default_factory=dict)  # key=id(block)
